project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
  

  
# freezing seems to bork font size
execute:
  freeze: auto  # Re-render only when source changes
  
website:
  title: "Math Camp"
  description: "NU Social Science Math Camp"
  search: true
  page-navigation: false
  sidebar:
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/gustavo-diaz/NUmathcamp
        text: "Source code"
      - icon: cloud-fill
        href: https://posit.cloud/
        text: "Posit Cloud"
        
    style: "docked"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "Home"
      - section: "Math"
        contents:
            - text: "1. Notations, sets, functions"
              file: math/01_notation.qmd
            - text: "2. Matrices"
              file: math/02_matrices.qmd
            - text: "3. Calculus I"
              file: math/03_calc1.qmd
            - text: "4. Calculus II"
              file: math/04_calc2.qmd
      - section: "Programming"
        contents:
            - text: "1. Getting started"
              file: r/01_intro.qmd
            - text: "2. Tidyverse I"
              file: r/02_tidy1.qmd
            - text: "3. Tidyverse II"
              file: r/03_tidy2.qmd
            - text: "4. Sampling and simulation"
              file: r/04_sampling.qmd

format:
  html:
    theme: 
      light: [flatly, custom.scss]
      dark: [darkly, custom_dark.scss]

